config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :oxford_learners_dictionaries, only: :index do
    collection do
      get :search
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/oxford_learners_dictionaries_controller.rb
class OxfordLearnersDictionariesController < ApplicationController
  def search
    if params[:oxford_learners_dictionaries]
      word = params[:oxford_learners_dictionaries][:word]
      @oxford = OxfordLearnersDictionaries::English.new(word).look_up unless word.blank?
    end
    render :index, status: status_oxford
  end

  private
  def status_oxford
    @oxford.nil? ? 422 : 200
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<p>
  Easy interface to test my own gems! \o/
</p>
<p>
  <%= link_to 'OxfordLearnersDictionaries::English', search_oxford_learners_dictionaries_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GemsTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/oxford_learners_dictionaries/index.html.erb
<%= link_to 'Home', root_url %>

<br/>
<br/>

<%= simple_form_for :oxford_learners_dictionaries, :url => '/oxford_learners_dictionaries/search', method: :get do |f| %>
  <%= f.input :word, as: :string %>
  <%= f.button :submit %>
<% end %>

<br/>

<p>
  DEFINITION
</p>

<% if @oxford %>
  <% @oxford.each do |key, value| %>
  <p>
    <%= key %>: <%= value %>
  </p>
  <% end %>
<% end %>